Cosmetics, typo fixes

diff --git a/qcow2-to-box b/qcow2-to-box
--- a/qcow2-to-box
+++ b/qcow2-to-box
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 if [ $# -ne 1 ]; then
-  echo "Usage: $(basename $0) <qcow image>" 2>&1
+  echo "Usage: $(basename $0) <qcow image>" 1>&2
   exit 1
 fi
 
@@ -10,17 +10,17 @@ dir="$(dirname "$img")"
 box="$(basename "${img%.*}.box")"
 
 if ! qemu-img info "$img" | grep -qi qcow; then
-  echo "Not a qcow image: $img" 2>&1
+  echo "Not a qcow image: $img" 1>&2
   exit 1
 fi
 
 if [ ! -w "$dir" ]; then
-  echo "No write permission to $dir, aborting!" 2>&1
+  echo "No write permission to $dir, aborting!" 1>&2
   exit 1
 fi
 
 if [ -f "$dir/$box" ]; then
-  echo "$dir/$box already exists, aborting!" 2>&1
+  echo "$dir/$box already exists, aborting!" 1>&2
   exit 1
 fi
 
