Fix typo

diff --git a/ca-setup/setup-ca b/ca-setup/setup-ca
--- a/ca-setup/setup-ca
+++ b/ca-setup/setup-ca
@@ -1,7 +1,7 @@
 #!/bin/sh
 
-if [ "$(which certtool 2> /dev/null)" != "" ]; then
-  echo "certtool is not found, install gnutls-utils" 1>&2
+if [ "$(which certtool 2> /dev/null)" = "" ]; then
+  echo "certtool not found, install gnutls-utils" 1>&2
   exit 1
 fi
 
